### ISSUE TITLE
Do you know how to solve the digital signature certificate issue?

### ISSUE THREAD

**Issue by GF-Huang** [riverar/messageanalyzer-archive#2] opened 2021-11-21 16:06 UTC
![image](https://user-images.githubusercontent.com/4510984/142769573-503fbb57-c72f-4294-b837-9def6aa394d2.png)

Translation by Google:

Fail to start live consumer Unable to start session for Firewall provider. Windows cannot verify the digital signature of this file. Some software or hardware has been changed recently. A file with an incorrect signature or a damaged file may be installed, or the installed file may be malicious software of unknown origin.

**Comment by riverar** [comment] 2022-06-10 15:48
Oh, let me look into that. You'll probably have to resign some files.

**Comment by riverar** [comment] 2024-05-30 01:57
Sorry for the delay. I can't reproduce this. Can you provide some repro steps? Closing for now.

**Closed as not planned by riverar** 2024-05-30 01:57 UTC
